config/routes.rb
require 'main_domain_constraint'
require 'personalized_domain_constraint'

Heritage::Application.routes.draw do

  get "photos/create"
  get "photos/destroy"

  devise_for :users

  namespace :as do |sd|
    resources :photos do as_routes end
    resources :users do as_routes end
    resources :stories do as_routes end
    resources :emails do as_routes end
  end

  resources :stories do
    resources :photos, :only => [:create, :destroy, :edit, :update, :show] do
      member do
        get :purchase
      end
    end
    member do
      post :sort
      get :editlong
      get :thumbs
      put :updatelong
    end
  end

  resources :emails, :only => [:create, :index, :destroy] do
    collection do
      get :export
    end
  end

  resources :photographers do
    member do
      post :sort
      get :about
      get :contact
    end
  end

  resource :shop

  resource :cart do
    member do
      post :add
      put :add
      post :update_item
      post :set_coupon
      get :remove_item
    end
  end

  resource :account do
    member do
      get :social_medias
      get :website
      get :stories
    end
    resources :available_sizes
    resources :coupons
    put :update_avatar
    put :update_main_photo
    delete :delete_main_photo
  end

  constraints :subdomain => "admin" do
    root :to => "admin#index"
  end

  constraints(PersonalizedDomainConstraint.new) do
    match 'about' => 'photographers#about'
    match 'contact' => 'photographers#contact'
    root :to => "photographers#show"
  end

  constraints(MainDomainConstraint.new) do
    root :to => "heritage#index"
  end

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  match ':controller(/:action(/:id))(.:format)'
end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :user
  has_many :photos, :order => "position", :dependent => :destroy
  acts_as_list :scope => :user_id

  scope :public, where(is_private: false)
  scope :private, where(is_private: true)

  acts_as_taggable
  has_permalink

  validates_presence_of :user_id, :title
  validates_uniqueness_of :title, :scope => :user_id

  attr_accessible :title, :description, :tag_list, :is_private

  def max_photo_height(width=nil)
    max_height = photos.sort{|a,b| a.height <=> b.height }.last

    if width
      max_height.photo_dimension([width, width]).last
    else
      max_height.photo_dimension.last
    end
  end

  def any_for_sale?
    self.user.allow_sale && self.photos.for_sale.any?
  end

  def max_photo_width
    photos.sort{|a,b| a.width <=> b.width }.last.photo_dimension.first
  end

  before_create :set_private
  def set_private
    self.is_private = true
  end

#  protected
#  before_save :generate_permalinkifblank
#  def generate_permalinkifblank
#    if self.title.blank?
#      self.permalink = self.id.to_s
#    end
#
#    true
#  end
end

app/controllers/as/stories_controller.rb
class As::StoriesController < AsController
  active_scaffold :story do |config|
    config.columns.exclude :is_private, :position
    config.list.sorting = { :id => :desc }
  end
end 

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :show, :thumbs]
  before_filter :get_story, :only => [:update, :edit, :destroy, :sort, :editlong, :updatelong]
  before_filter :get_stories, :only => [:edit, :sort, :editlong, :new, :updatelong, :create]
  before_filter :set_title

  def index
    raise ActiveRecord::RecordNotFound unless @photographer

    @stories = @photographer.stories.public(:order => 'id DESC')
    respond_to do |format|
      format.html
      format.atom
    end
  end

  def thumbs
    @story = Story.find_by_permalink(params[:id], :include => [:photos])
    raise ActiveRecord::RecordNotFound unless @story

    @title = "#{@story.user.name}: #{@story.title}"
    render :layout => "story"
  end

  def show
    @story = Story.find_by_permalink(params[:id], :include => [:photos])
    raise ActiveRecord::RecordNotFound unless @story

    @photo = @story.photos.first if @story.photos.any?
    @title = "#{@story.user.name}: #{@story.title}"
    render :layout => "story"
  end

  def new
    @story = Story.new
    render :layout => "adminfixed"
  end

  def edit
    render :layout => "adminfixed"
  end

  def editlong
    render :layout => "adminfixed"
  end

  def updatelong
    Photo.transaction do 
      @story.photos.each do |photo|
        if !photo.update_attributes(params["photos_#{photo.id}".to_sym])
          logger.info "Can't save #{photo}: #{photo.errors.full_messages.to_sentence}"
        end
      end
    end
    flash[:message] = "Photos have been updated"
    redirect_to :action => :editlong
  end

  def sort
    Photo.transaction do
      @story.photos.each do |photo|
        photo.position = params[:sortable].index(photo.id.to_s)
        photo.save
      end
    end
    render :nothing => true
  end

  def update
    if @story.update_attributes(params[:story])
      flash[:notice] = "Story was saved"
      redirect_to :action => 'edit'
    else
      flash.now[:alert] = "Can't save the story" 
      render :action => 'edit'
    end
  end
  
  def destroy
    @story.destroy
    redirect_to stories_account_path
  end

  def create
    @story = Story.new(params[:story])
    @story.user = current_user
    if @story.save
      redirect_to :action => :edit, :id => @story.permalink
    else
      render :new
    end
  end

  protected
end

app/helpers/as/stories_helper.rb
module As::StoriesHelper
  def story_photos_column(record, column)
    result = ""
    record.photos.each do |photo|
      result << image_tag(photo.image_url(:thumb), :width => 30, :height => 30)
    end
    result.html_safe
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= semantic_form_for @story do |f| %>
	<%= f.inputs :name => "Basic" do %>
		<%= f.input :title %>
		<%= f.input :description, :input_html => { :class => 'input-xlarge', :rows => 10 } %>
		<span class="help-block">
			You can change all this later, after you uploaded your photos.
		</span>
	<% end %>

	<%= f.actions do %>
		<%= f.action :submit, :as => :button,:button_html => { :class => "btn btn-primary" } %>
		<%= f.action :cancel, :as => :link, :label => "Cancel" %>
	<% end %>
<% end %>

app/views/stories/_front_story.html.erb
    <div id="slider" class="carousel slide" style="height: <%= front_story.photos.first.photo_dimension.last %>px">
      <div class="carousel-inner">
          <%= link_to(image_tag(front_story.photos.first.image_url(:web),
            :width => 800,
            :height => front_story.photos.first.photo_dimension.last), story_path(front_story)) %>
		  </div>
		</div>

app/views/stories/_left.html.erb
<ul class="nav nav-list">

  <% if @photographer.stories.public.any? %>
  <li class="nav-header">Public Stories</li>
  <% @photographer.stories.public.each do |story| %>
  <li class="<%= 'active' if story == @story %>">
  <%= link_to story.title, edit_story_path(story) %>
  </li>
  <% end %>
  <% end %>

  <% if @photographer.stories.private.any? %>
  <li class="nav-header">Private Stories</li>
  <% @photographer.stories.private.each do |story| %>
  <li class="<%= 'active' if story == @story %>">
  <%= link_to story.title, edit_story_path(story) %>
  </li>
  <% end %>
  <% end %>
</ul>

app/views/stories/_photo.html.erb
<li class="ui-state-default" id="sortable_<%= photo.id %>">
	<%= image_tag photo.image_url if photo.image? %>
</li>

app/views/stories/_thumbnails.html.erb
<div id="photos">
	<ul class="thumbnails_main">
	<% @stories.each do |story| %>
		<% if story.photos.any? && story.photos.first.image? %>
			<% photo = story.photos.first %>

			<li>
			<h3><%= story.title %></h3>
			<%= link_to(image_tag(photo.image_url(:thumb), :width => 170, :height => 170),
									story_url(story),
									:class => "thumbnail") %>
			<p>
			<%# story.description %>
			</p>
			</li>

		<% end %>
	<% end %>
  </ul>
  <div class="clearfix"></div>
</div>

app/views/stories/edit.html.erb
<% key = Rails.application.config.session_options[:key] %>

<%= content_for :head_script do %>
<script type="text/javascript">
		$(document).ready(function() {
			// Handler for .ready() called.
				$("#sortable" ).sortable({ 
					revert: true,
					stop: function(e,ui) {
						$.ajax({
							data: $('#sortable').sortable('serialize'),
							type: 'POST',
							url: '<%= sort_story_path(@story) %>',
							success: function () {
							// it worked!  
							},
							error: function (response) {
							// we had an error
							}
						});
						
					}
					
					});
				$("#sortable").disableSelection();

				var $modal = $('#ajax-modal');

				$('.ajax .demo').on('click', function(){
						// create the backdrop and wait for next modal to be triggered
						$('body').modalmanager('loading');

						setTimeout(function(){
							$modal.load('modal_ajax_test.html', '', function(){
								$modal.modal();
								});
							}, 1000);
						});



				/*
				$('body').on('hidden', '.modal', function () {
						$(this).removeData('modal');
						});
						*/
		});
</script>
<% end %>
<%= content_for :scripts do %>
<script type="text/javascript">
    var upload_params = {
			'<%= key %>' : '<%= cookies[key] %>',
			'<%= request_forgery_protection_token %>' : '<%= form_authenticity_token %>',
      '_http_accept': 'application/javascript'
    };
    var url = $('input#photo_image').attr('rel');
    $('input#photo_image').uploadify({
      'swf'            : '/assets/uploadify.swf',
      'uploader'       : url,
      'fileObjName'	   : 'photo[image]',
      'fileTypeExts'   : '*.png;*.jpg;*.gif;*.tif',
      'multi'          : true,
      'formData'       : upload_params,
      'auto'           : true,
      'onUploadSuccess' : function(file, data, response) {
        $('#sortable').append(data);
      }
    });
	</script>
<% end %>

     <div class="row">
        <div class="span2 well">
          <%= render partial: "stories/left" %>
        </div>
        <div class="span6">
				<%= semantic_form_for @story, :url => story_path, :html => {:method => :put} do |f| %>
							<%= f.inputs :name => "Story information" do %>
								<%= f.input :title, :input_html => { :class => 'input-xxlarge'},
                  :hint => "Your story public link is #{link_to(story_url(@story, host: @photographer.specific_url),
                    story_url(@story, host: @photographer.specific_url))}".html_safe %>
								<%= f.input :description, :input_html => { :class => 'autogrow input-xxlarge', :rows => 10, :cols => 40 } %>
								<%= f.input :tag_list, :input_html => { :class => 'input-xxlarge' }, :hint => "Enter, your, tags, with, commas" %>
                <%= f.input :is_private, hint: "foobar", label: "Private" %>
							<% end %>

							<%= f.actions do %>
								<%= f.action :submit, :as => :button, :button_html => { :class => "btn btn-primary" } %>
								<%= link_to "Cancel", story_path(@story), :class => "btn" %>
								or <%= link_to "delete this story", story_path(@story), :data => { :confirm => "Are you sure?" }, :method => :delete  %>
							<% end %>
						<div id="ajax-modal" class="modal hide fade" tabindex="-1"></div>

						<div id="responsive" class="modal hide fade" tabindex="-1">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
								<h3 id="myModalLabel">Editing Photo properties</h3>
							</div>
							<div class="modal-body">
							</div>
							<div class="modal-footer">
								<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
							</div>
						</div>

						<div class="btn-toolbar">
							<div class="btn-group pull-right">
								<button type="button" class="btn"><a href="<%= editlong_story_path(@story) %>"><i class="icon-th-large"></i></a></button>
								<button type="button" class="btn"><i class="icon-th"></i></button>
							</div>
							<div class="clearfix"></div>
						</div>

						<%= f.inputs :name => "Story Photos" do %>
							<div id="photos thumbnails">
								<ul id="sortable">
									<% @story.photos.each do |photo| %>
										<li class="ui-state-default" id="sortable_<%= photo.id %>">
										<% if photo.image? %>
											<%= link_to image_tag(photo.image_url(:thumb), :alt => "Photo #{photo.id}"), 
												edit_story_photo_path(@story, photo.permalink || photo.id), {
												:class => "thumbnail", 'data-cache' => 'false', 
												'data-toggle' => 'modal', 'data-target' => '#myModal'
											}  %>
										<% end %>
										</li>
									<% end %>
								</ul>
								<div style="clear: both;"></div>
							</div>
							<% unless @story.new_record? %>
								<%= fields_for Photo.new do |f| %>
									<%= f.file_field :image, :rel => story_photos_path(@story) %>
								<% end %>
							<% end %>
						<% end %>
		<% end %>
</div>
</div>

app/views/stories/editlong.html.erb
<%= content_for :head_script do %>
<script type="text/javascript">
		$(document).ready(function() {
			// Handler for .ready() called.
				$("#sortable" ).sortable({ 
					revert: true,
					stop: function(e,ui) {
						$.ajax({
							data: $('#sortable').sortable('serialize'),
							type: 'POST',
							url: '<%= sort_story_path(@story) %>',
							success: function () {
							// it worked!  
							},
							error: function (response) {
							// we had an error
							}
						});
						
					}
					
					});
				$("#sortable").disableSelection();

				$('body').on('hidden', '.modal', function () {
						$(this).removeData('modal');
				});
		});
</script>
<% end %>

     <div class="row">
        <div class="span2 well">
          <%= render partial: "stories/left" %>
        </div>
        <div class="span8">
						<%= form_for @story, :url => updatelong_story_path, :html => {:method => :put} do |f| %>

						<div class="btn-toolbar">
							<div class="btn-group pull-right">
								<button type="button" class="btn"><i class="icon-th-large"></i></button>
								<button type="button" class="btn"><a href="<%= edit_story_path(@story, :anchor => "tab2") %>"><i class="icon-th"></i></a></button>
							</div>
							<div class="clearfix"></div>
						</div>

						<div class="row-fluid">
							<ul class="thumbnails">
									<% @story.photos.each do |photo| %>
										<li class="ui-state-default thumbnail">
											<% if photo.image? %>
												<%= image_tag(photo.image_url(:thumb), :alt => "Photo #{photo.id}") %>
											<% end %>

											<div class="caption">
												<%= text_field "photos_#{photo.id}", :title, :value => photo.title, :class => 'input-large', :placeholder => "title" %>
												<div>
													<%= text_area "photos_#{photo.id}", :description, 
														:value => photo.description, 
														:class => 'input-large', 
														:rows => 3, 
														:placeholder => "description" %>
												</div>
												<div>
													<%= text_field "photos_#{photo.id}", :tag_list, :value => photo.tag_list, :class => 'input-large', :placeholder => "tag1, tag2" %>
												</div>
												<label class="checkbox">
													<%= check_box "photos_#{photo.id}", :for_sale, :checked => photo.for_sale, :class => 'input-large' %> For sale
												</label>

												<%= link_to "delete this photo", story_photo_path(@story.id, photo.id), :data => { :confirm => "Are you sure?" }, :method => :delete  %>
											</div>
										</li>
									<% end %>
							</ul>
						</div>
						<fieldset class="form-actions">
							<button class="btn btn-primary" name="button" type="submit">Update Photos</button>
							<a href="/stories/2nd" class="btn">Cancel</a>
						</fieldset>
					<% end %>
        </div>
      </div>

app/views/stories/index.html.erb
<ul>
	<% @stories.each do |story| %>
		<li><%= link_to story.title, :action => :show, :id => story %></li>
	<% end %>
</ul>

app/views/stories/new.html.erb
<%= render :partial => 'form' %>

app/views/stories/show.html.erb
<% if @story.photos.any? %>
 <%= content_for :facebook_meta do %>
  <%= tag(:meta, property: 'og:url', content: story_url(@story)) %>
  <%= tag(:meta, property: 'og:image',
                  content: full_image_link(@story.photos.first.image_url(:web))) %>
  <%= tag(:meta, property: 'og:title', content: "#{@story.title} - #{@story.user.name}" ) %>
  <%= tag(:meta, property: 'og:description', content: @story.description) %>
  <%= tag(:meta, property: 'og:site_name', content: @story.user.name) %>
 <% end %>
<% end %>
<%= content_for :head_script do %>
	<script type="text/javascript">
		$(document).ready(function() {
      var slider = $('.carousel').carousel('pause')
        .bind('slid', function() {
        var index = $(this).find(".active").index();
        $('#photos_index').html(index + 1);
      });

      jQuery(document).bind('keyup', function(e) {
        if(e.which==39){
          jQuery('.icon-chevron-right').trigger('click');
        } else if(e.which==37){
          jQuery('.icon-chevron-left').trigger('click');
        }
      });
		});
	</script>
<% end %>

<div id="story">

<% if @story.photos.any? %>
    <div id="myCarousel" class="carousel slide" style="height: <%= @story.max_photo_height(Photo::RESIZE_TO_FIT.first) %>px">

    <div class="carousel-inner">
      <% @story.photos.each_with_index do |photo,i| %>
      <% @photo_index = (i+1) if @photo == photo %>
      <div class="item <%= 'active' if @photo == photo %>">
        <%= link_to(image_tag(photo.image_url(:web),
          :width => Photo::RESIZE_TO_FIT.first,
          :style => "margin-top: #{(@story.max_photo_height(Photo::RESIZE_TO_FIT.first) - photo.photo_dimension(Photo::RESIZE_TO_FIT).last) / 2}px; padding-bottom: #{(@story.max_photo_height(Photo::RESIZE_TO_FIT.first) - photo.photo_dimension(Photo::RESIZE_TO_FIT).last) / 2}px",
          :height => photo.photo_dimension.last),
        "#myCarousel", 'data-slide' => 'next', :class => "") %>

        <div class="carousel-caption">
          <div class="photo_description">
            <p class="pull-right">
            <% if @story.any_for_sale? %>
              <%= link_to "Purchase a print",
                purchase_story_photo_path(@story, photo.permalink || photo.id) %> | 
            <% end %>
            <%= link_to "Direct Link", story_photo_url(@story, photo.permalink || photo.id) %>
            </p>
            <p>
            <%= photo.description %>
            </p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>

  <div class="bottomnav">
    <div class="thumbs_link pull-right">
      <% if @story.any_for_sale? %>
        <%= link_to image_tag("cart.png", width: 25), 
          story_photo_path(@story), id: "purchase_link" %>
      <% end %>
      <%= link_to content_tag(:i, '', :class => "icon-th-large", :title => "Thumbnails"),
      thumbs_story_path(@story) %>
      <%= link_to content_tag(:i, '', :class => "icon-chevron-left", :title => "Previous"),
        "#myCarousel", 'data-slide' => 'prev' %>
      <%= link_to content_tag(:i, '', :class => "icon-chevron-right", :title => "Next"),
        "#myCarousel", 'data-slide' => 'next' %>
    </div>
    <div id="photos_counter">
      <span id="photos_index"><%= @photo_index %></span>/<%= @story.photos.count %>
    </div>
    <div class="clearfix"></div>
  </div>

  <div id="story_description">
    <h3><%= @story.title %></h3>
    <%= @story.description %>
  </div>
<% end %>
</div>

app/views/stories/thumbs.html.erb
<%= content_for :facebook_meta do %>

  <%= tag(:meta, property: 'og:url', content: story_url(@story)) %>
  <% if @story.photos.any? %>
    <%= tag(:meta, property: 'og:image',
                  content: full_image_link(@story.photos.first.image_url(:web))) %>
  <% end %>
  <%= tag(:meta, property: 'og:title', content: "#{@story.title} - #{@photographer.name}" ) %>
  <%= tag(:meta, property: 'og:description', content: @story.description) %>
  <%= tag(:meta, property: 'og:site_name', content: @photographer.name) %>

<% end %>

<div id="photos">
  <ul class="thumbs">
    <% @story.photos.each_with_index do |photo,i| %>
    <li class="ui-state-default">
    <div class="thumbs_outer">
      <div class="thumbs_inner thumbs_image">
        <%= link_to image_tag(photo.image_url(:thumb)), 
        story_photo_path(@story, photo.permalink || photo.id) %>
      </div>
      <div class="thumbs_inner thumbs_background"></div>
      <div class="thumbs_info" id="thumbs_info_<%= photo.id %>">
        <div class="thumbs_text">
          <% if photo.description %>
          <br/>
          <%= photo.description %>
          <% else %>
          <%= i + 1 %>
          <% end %>
        </div>
      </div>
    </div>
    </li>
    <% end %>
</ul>
  <div id="story_description">
    <h3><%= @story.title %></h3>
    <%= @story.description %>
  </div>
</div>