config/routes.rb
require 'main_domain_constraint'
require 'personalized_domain_constraint'

Heritage::Application.routes.draw do

  get "photos/create"
  get "photos/destroy"

  devise_for :users

  namespace :as do |sd|
    resources :photos do as_routes end
    resources :users do as_routes end
    resources :stories do as_routes end
    resources :emails do as_routes end
  end

  resources :stories do
    resources :photos, :only => [:create, :destroy, :edit, :update, :show] do
      member do
        get :purchase
      end
    end
    member do
      post :sort
      get :editlong
      get :thumbs
      put :updatelong
    end
  end

  resources :emails, :only => [:create, :index, :destroy] do
    collection do
      get :export
    end
  end

  resources :photographers do
    member do
      post :sort
      get :about
      get :contact
    end
  end

  resource :shop

  resource :cart do
    member do
      post :add
      put :add
      post :update_item
      post :set_coupon
      get :remove_item
    end
  end

  resource :account do
    member do
      get :social_medias
      get :website
      get :stories
    end
    resources :available_sizes
    resources :coupons
    put :update_avatar
    put :update_main_photo
    delete :delete_main_photo
  end

  constraints :subdomain => "admin" do
    root :to => "admin#index"
  end

  constraints(PersonalizedDomainConstraint.new) do
    match 'about' => 'photographers#about'
    match 'contact' => 'photographers#contact'
    root :to => "photographers#show"
  end

  constraints(MainDomainConstraint.new) do
    root :to => "heritage#index"
  end

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  match ':controller(/:action(/:id))(.:format)'
end

app/controllers/photographers_controller.rb
class PhotographersController < ApplicationController
  layout 'story'
  before_filter :set_title

  def show
    if params[:id]
      @photographer = User.find_by_permalink(params[:id], :include => [:stories]) ||
        User.find(params[:id], :include => [:stories])
    end
    @photographer ||= @current_photographer

    raise ActiveRecord::RecordNotFound unless @photographer

    @stories = @photographer.stories.public(include: [:photos])
    @stories.each do |story|
      if story.photos.any?
        @front_story = story
        break
      end
    end
  end

  set_tab :contact, only: [:contact]
  set_tab :about, only: [:about]
  set_tab :home, only: [:show]
  def contact
  end

  def about
    @stories = @photographer.stories.public(include: [:photos])
  end

  def index
    @photographers = User.all(:include => [:stories])
  end

  before_filter :authenticate_user!, :only => [:edit, :update, :sort]
  before_filter :get_photographer, :only => [:edit, :update, :sort]
  def edit
    render :layout => "adminfixed"
  end

  def update
    if @photographer.update_attributes(params[:user])
      flash[:notice] = "Info was saved"
      redirect_to :action => 'edit'
    else
      flash.now[:alert] = "Can't save the story"
      render :action => 'edit'
    end
  end

  def sort
    Story.transaction do
      current_user.stories.each do |story|
        story.position = params[:sortable].index(story.id.to_s)
        story.save
      end
    end
    render :text => "OK"
  end

  protected

  def get_photographer
    @photographer = current_user
  end
end

app/helpers/photographers_helper.rb
module PhotographersHelper
end

app/views/photographers/_about.html.erb
<div class="about">
	<%= image_tag(user_avatar(@current_photographer), :class => "pull-right") %>

	<p class="lead">
	<% if @photographer.description %>
		<%= @markdown.render(@photographer.description).html_safe %>
	<% end %>
	</p>
	<div class="clearfix"></div>
</div>

app/views/photographers/_story.html.erb
<li class="ui-state-default" id="sortable_<%= story.id %>">
<a href="<%= edit_story_path(story) %>">
	<% if story.photos.any? && story.photos.first.image? %>
		<%= image_tag story.photos.first.image_url(:thumb) %>
	<% else %>
		No Photos
	<% end %>
</a>
</li>

app/views/photographers/about.html.erb
<%= content_for :facebook_meta do %>
	<meta property="og:url" content="<%= about_url %>" />
  <% if @photographer.avatar? %>
    <meta property="og:image" content="<%= full_image_link @photographer.avatar_url(:thumb) %>" />
  <% end %>
	<meta property="og:title" content="<%= @photographer.name %> - Photography" />
	<meta property="og:description" content="<%= @photographer.description %>" />
	<meta property="og:site_name" content="<%= @photographer.name %>"/>
<% end %>
<%= render :partial => 'photographers/about' %>

app/views/photographers/contact.html.erb
<%= content_for :facebook_meta do %>
	<meta property="og:url" content="<%= contact_url %>" />
	<% if @photographer.avatar? %>
		<meta property="og:image" content="<%= full_image_link @photographer.avatar_url(:thumb) %>" />
	<% end %>
	<meta property="og:title" content="<%= @photographer.name %> - Photography" />
	<meta property="og:description" content="<%= @photographer.description %>" />
	<meta property="og:site_name" content="<%= @photographer.name %>"/>
<% end %>

<div class="about">
  <%= image_tag(user_avatar(@current_photographer), :class => "pull-right") %>

  <p class="lead">
  <% if @photographer.contact %>
  <%= @markdown.render(@photographer.contact).html_safe %>
  <% end %>
  </p>

	<p class="lead">
	<% if !@photographer.facebook_url.blank? %>
		<%= link_to "Facebook", @photographer.facebook_url, :class => "btn" %>
	<% end %>
	<% if !@photographer.twitter_url.blank? %>
		<%= link_to "Twitter", @photographer.twitter_url, :class => "btn" %>
	<% end %>
	<% if !@photographer.blog_url.blank? %>
		<%= link_to "Blog", @photographer.blog_url, :class => "btn" %>
	<% end %>
	</p>
	<div class="clearfix"></div>
</div>

app/views/photographers/index.html.erb
<ul>
	<% @photographers.each do |photographer| %>
		<li><%= link_to photographer.email, photographer_url(photographer) %></li>
	<% end %>
</ul>

app/views/photographers/show.html.erb
<% if @photographer.stories.any? && @photographer.stories.first.photos.any? %>
<%= content_for :facebook_meta do %>
	<meta property="og:url" content="<%= root_url %>" />
	<meta property="og:image" content="<%= full_image_link @photographer.stories.first.photos.first.image_url(:web) %>" />
	<meta property="og:title" content="<%= @photographer.name %> - Photography" />
	<meta property="og:description" content="<%= user_description_text(@photographer) %>" />
	<meta property="og:site_name" content="<%= @photographer.name %>"/>
<% end %>
<% end %>

<% if @photographer.main_photo? %>
<%= image_tag(@photographer.main_photo_url(:web), :width => 960, :height => 960) %>
<% else %>
  <%= render :partial => 'stories/front_story',
   object: @front_story if @front_story %>
<% end %>

<%= render :partial => 'stories/thumbnails' %>