config/routes.rb
require 'main_domain_constraint'
require 'personalized_domain_constraint'

Heritage::Application.routes.draw do

  get "photos/create"
  get "photos/destroy"

  devise_for :users

  namespace :as do |sd|
    resources :photos do as_routes end
    resources :users do as_routes end
    resources :stories do as_routes end
    resources :emails do as_routes end
  end

  resources :stories do
    resources :photos, :only => [:create, :destroy, :edit, :update, :show] do
      member do
        get :purchase
      end
    end
    member do
      post :sort
      get :editlong
      get :thumbs
      put :updatelong
    end
  end

  resources :emails, :only => [:create, :index, :destroy] do
    collection do
      get :export
    end
  end

  resources :photographers do
    member do
      post :sort
      get :about
      get :contact
    end
  end

  resource :shop

  resource :cart do
    member do
      post :add
      put :add
      post :update_item
      post :set_coupon
      get :remove_item
    end
  end

  resource :account do
    member do
      get :social_medias
      get :website
      get :stories
    end
    resources :available_sizes
    resources :coupons
    put :update_avatar
    put :update_main_photo
    delete :delete_main_photo
  end

  constraints :subdomain => "admin" do
    root :to => "admin#index"
  end

  constraints(PersonalizedDomainConstraint.new) do
    match 'about' => 'photographers#about'
    match 'contact' => 'photographers#contact'
    root :to => "photographers#show"
  end

  constraints(MainDomainConstraint.new) do
    root :to => "heritage#index"
  end

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/active_scaffold.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Heritage" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "active_scaffold", :media => "all" %>

    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "active_scaffold" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Heritage</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li class=""><%= link_to "Home", "/"  %></li>
							<li class="divider-vertical"></li>

							<li><%= link_to "Stories", "#", :class => "dropdown-toggle", 'data-toggle'=>"dropdown" %>
								<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
									<% @stories.each do |story| %>
										<li><%= link_to story.title, edit_story_path(story) %></li>
									<% end %>

									<li class="divider"></li>
									<li><%= link_to "Create a story", new_story_path %></li>
								</ul>

							</li>

              <li><%= link_to "Statistics", ""  %></li>
            </ul>
						<div class="pull-right">
							<ul class="nav">
								<li class="dropdown">
								<%= link_to current_user.email, "#", :class => "dropdown-toggle", 'data-toggle'=>"dropdown" %> 
								<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
									<li><%= link_to "Edit your account", edit_account_path %></li>
									<li class="divider"></li>
									<li><%= link_to "Logout", destroy_user_session_path(:method => :delete) %></li>
								</ul>
								</li>
							</ul>
						</div>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container" style="padding-top: 60px;">
			<%= yield %>
      <footer>
        <p>&copy; Fabien Penso 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

  </body>
</html>

app/views/layouts/adminfixed.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Heritage" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "admin", :media => "all" %>

    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "jquery-ui" %>
		<%= yield :head_script %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Heritage</a>
          <div class="container nav-collapse">
            <ul class="nav">
							<%= tabs_tag(:builder => BoostrapTabs,
													 :open_tabs => { :class => "nav" }) do |tab| %>
								<%= tab.home 'Home', root_path %>

								<li class="divider-vertical"></li>

								<% if current_user %>
									<li class="dropdown" class="name">
									<%= link_to "Stories <b class='caret'></b>".html_safe, "#",
										:class => "dropdown-toggle",
										'data-toggle'=>"dropdown" %>

										<ul class="dropdown-menu">
											<li><%= link_to "Create a story", new_story_path %></li>
											<li>
											<%= link_to "All Stories", stories_account_path %>
											</li>
											<li class="divider"></li>
											<% @stories.each do |story| %>
												<li><%= link_to "#{story.title} (#{story.photos.count})", edit_story_path(story) %></li>
											<% end %>
										</ul>

										</li>
									<% end %>

								<%= tab.account "Your Account", edit_account_path %>
								<%= tab.audience "Your Audience", emails_path %>
								<% if @photographer && @photographer.specific_url %>
									<%= tab.public_website "Your Public Website", "http://#{@photographer.specific_url}" %>
								<% end %>
							<% end %>

						</ul>
						<div class="pull-right">
							<ul class="nav">
								<% if current_user %>
                  <li class="dropdown name">
                  <%= image_tag(user_avatar(current_user, :thumb), 
                      :width => 20, :height => 20, :class => 'small-avatar pull-left') %>
									<%= link_to "#{current_user.email} <b class='caret'></b>".html_safe, "#", :class => "dropdown-toggle", 'data-toggle'=>"dropdown" %> 
									<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
										<li><%= link_to "Edit your account", edit_account_path %></li>
										<li class="divider"></li>
										<li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
									</ul>
									</li>
								<% else %>
								<% end %>
							</ul>
						</div>
					</div><!--/.nav-collapse -->
				</div>
			</div>
		</div>


		<div class="container" style="padding-top: 60px;">
			<%= render :partial => 'shared/top_flash' %>

			<%= yield %>

			<footer>
			</footer>

		</div> <!-- /container -->

		<%= yield :scripts %>
	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Heritage</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a class="brand" href="/">Heritage</a>
				<div class="nav-collapse">
					<%# tabs %>
				</div>
			</div>
		</div>
	</div>

	<div class="container">
		<%= render :partial => 'shared/top_links' %>

		<p>
		<%= current_user.email if current_user %>
		</p>

		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>

		<%= yield %>
	</div>

</body>
</html>

app/views/layouts/fixedlayout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Heritage" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>
		<%= yield :head_script %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Heritage</a>
          <div class="container nav-collapse">
            <ul class="nav">
							<li><%= link_to "Stories", :controller => '/stories' %></li>
              <li><%= link_to "Photographers", photographers_path  %></li>
              <li><%= link_to "Newsletter", "/path3"  %></li>
							<li>
							<%= link_to(current_user.email, edit_user_registration_path) if current_user %>
							</li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container topmargin">
			<%= yield %>

      <footer>
			<p>&copy; Fabien Penso 2012 | <a href="">get yours</a></p> - fixedlayout
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

		<%= yield :scripts %>
  </body>
</html>

app/views/layouts/heritage.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Heritage: Open Source gallery</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">
	<style type="text/css">
		body {
			padding-top: 20px;
			padding-bottom: 40px;
		}

		/* Custom container */
		.container-narrow {
			margin: 0 auto;
			max-width: 700px;
		}
		.container-narrow > hr {
			margin: 30px 0;
		}

		/* Main marketing message and sign up button */
		.jumbotron {
			margin: 60px 0;
			text-align: center;
		}
		.jumbotron h1 {
			font-size: 72px;
			line-height: 1;
		}
		.jumbotron .btn {
			font-size: 21px;
			padding: 14px 24px;
		}

		/* Supporting marketing content */
		.marketing {
			margin: 60px 0;
		}
		.marketing p + h4 {
			margin-top: 28px;
		}
	</style>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container-narrow">
		<%= yield %>
	</div>
</body>
</html>

app/views/layouts/story.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= yield :facebook_meta %>

    <title><%= @title ? @title : "Heritage" %></title>
    <%= csrf_meta_tags %>

		<link href='http://fonts.googleapis.com/css?family=Titillium+Web' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "global", :media => "all" %>

    <%= javascript_include_tag "application" %>
    <%# javascript_include_tag "bootstrap-carousel" %>
		<%= javascript_include_tag "jquery.flexslider-min" %>

		<%# stylesheet_link_tag "/stylesheets/global" %>

		<%= yield :head_script %>
  </head>
  <body>
		<div id="story_header_container">
			<div class="story_header">
				<div class="leftlogo">
					<%= link_to @photographer.name || "", root_url %>
				</div>
				<div class="navlinks">

          <% if !@photographer.description.blank? ||
            !@photographer.contact.blank? ||
            @photographer.any_for_sale? ||
            !@photographer.blog_url.blank? %>

           <%= tabs_tag(builder: BoostrapTabs,
            open_tabs: { :class => "nav nav-pills" }) do |tab| %>
            <% if @photographer.any_for_sale? %>
              <% if @cart.count > 0 %>
              <%= tab.cart "Your Cart (#{@cart.count})", cart_path %>
              <% end %>
              <%= tab.shop "Shop", shop_path %>
            <% end %>
            <% if !@photographer.description.blank? %>
              <%= tab.about 'About', about_path %>
            <% end %>
            <% if !@photographer.contact.blank? %>
              <%= tab.contact 'Contact', contact_path %>
            <% end %>
						<% if !@photographer.blog_url.blank? %>
							<%= tab.blog "Blog", @photographer.blog_url %>
						<% end %>
           <% end %>
          <% end %>

				</div>
			</div>
		</div>

		<div id="container">
			<%= yield %>
    <% if params[:controller] == 'stories' || params[:controller] == 'photos' %>
      <div class="copyright">
        <h1>
          © <%= @photographer.name %>. All Rights Reserved.
        </h1>
      </div>
    <% end %>
		</div> <!-- /container -->


    <% if params[:controller] == 'stories' || params[:controller] == 'photos' || params[:controller] == 'carts' %>
    <% else %>
    <%= render :partial => 'shared/footer' %>
    <% end %>

		<%= yield :scripts %>

		<% if @photographer.google_tracking_id %>
		<script type="text/javascript">

			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', '<%= @photographer.google_tracking_id %>']);
			_gaq.push(['_trackPageview']);

			(function() {
			 var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			 ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			 var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			 })();

		</script>
	  <% end %>
  </body>
</html>