config/routes.rb
require 'main_domain_constraint'
require 'personalized_domain_constraint'

Heritage::Application.routes.draw do

  get "photos/create"
  get "photos/destroy"

  devise_for :users

  namespace :as do |sd|
    resources :photos do as_routes end
    resources :users do as_routes end
    resources :stories do as_routes end
    resources :emails do as_routes end
  end

  resources :stories do
    resources :photos, :only => [:create, :destroy, :edit, :update, :show] do
      member do
        get :purchase
      end
    end
    member do
      post :sort
      get :editlong
      get :thumbs
      put :updatelong
    end
  end

  resources :emails, :only => [:create, :index, :destroy] do
    collection do
      get :export
    end
  end

  resources :photographers do
    member do
      post :sort
      get :about
      get :contact
    end
  end

  resource :shop

  resource :cart do
    member do
      post :add
      put :add
      post :update_item
      post :set_coupon
      get :remove_item
    end
  end

  resource :account do
    member do
      get :social_medias
      get :website
      get :stories
    end
    resources :available_sizes
    resources :coupons
    put :update_avatar
    put :update_main_photo
    delete :delete_main_photo
  end

  constraints :subdomain => "admin" do
    root :to => "admin#index"
  end

  constraints(PersonalizedDomainConstraint.new) do
    match 'about' => 'photographers#about'
    match 'contact' => 'photographers#contact'
    root :to => "photographers#show"
  end

  constraints(MainDomainConstraint.new) do
    root :to => "heritage#index"
  end

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  match ':controller(/:action(/:id))(.:format)'
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  set_tab :account, :except => [:stories]
  set_tab :home, :only => [:stories]
  layout "adminfixed"
  before_filter :authenticate_user!
  before_filter :get_photographer

  def show
  end

  def stories
    unless current_user.stories.any?
      flash[:notice] = "You should first create a story"
      redirect_to new_story_path
    end
  end

  def update
    if current_user.update_attributes(params[:user])
      flash[:notice] = "Info was saved"
      redirect_to :action => 'edit'
    else
      flash.now[:alert] = "Can't save the story" 
      render :action => 'edit'
    end
  end

  def delete_main_photo
    current_user.remove_main_photo!
    redirect_to website_account_path
  end

  def update_main_photo
    if current_user.update_attributes(params[:user])
      respond_to do |format|
        format.json {
          render :json => {:image_url => current_user.main_photo_url}.to_json
        }
      end
    end
  end
  def update_avatar
    if current_user.update_attributes(params[:user])
      respond_to do |format|
        format.json {
          render :json => {:image_url => current_user.avatar_url}.to_json
        }
      end
    end
  end

  def edit
  end

  def social_medias
  end

  def website
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_lefttabs.html.erb
					<%= nav_link("Your information", edit_account_path) %>
					<%= nav_link("Your social Medias", social_medias_account_path) %>
					<%= nav_link("Available sizes", account_available_sizes_path) %>
					<%= nav_link("Your Website", website_account_path) %>

app/views/accounts/edit.html.erb
			<div class="tabbable tabs-left">
				<ul class="nav nav-tabs">
					<%= render :partial => 'lefttabs' %>
				</ul>
				<div class="tab-content">
					<%= semantic_form_for @photographer, 
						:url => account_path, 
            :html => {:class => 'form form-horizontal', :method => :put, :multipart => true} do |f| %>

							<%= f.inputs :name => "Your information" do %>
								<div class="string input optional control-group">
									<label class="control-label" for="avatar"></label>
                  <div class="controls">
                  <%= image_tag(user_avatar(@photographer), :id => 'avatar', :width => 150) %>
								  </div>
								</div>
                <%= f.input :avatar, :as => :file %>
								<%= f.input :name, :input_html => { :class => 'input-xlarge' } %>
								<%= f.input :description, :input_html => { :class => 'input-xxlarge' } %>
                <%= f.input :contact, :input_html => { :class => 'input-xxlarge', :rows => 10 } %>
                <%= f.input :sale_description, :input_html => { :class => 'input-xxlarge', :rows => 10 } %>
                <div class="controls">
                  Use <%= link_to "the markdown", "http://daringfireball.net/projects/markdown/basics" %> syntax.
                </div>
							<% end %>

							<%= f.actions do %>
								<%= f.action :submit, :as => :button, :label => "Save", :button_html => { :class => "btn btn-primary btn-large" } %>
							<% end %>

						<% end %>
					</div>
				</div>
        <script type="text/javascript">
$(function() {
  $('#user_avatar').fileupload({
    dataType: 'json',
    url: '<%= update_avatar_account_path %>',
    done: function(e, data) {
      $('#avatar').attr("src", data.result.image_url);
    }
  });
});
        </script>

app/views/accounts/social_medias.html.erb
			<div class="tabbable tabs-left">
				<ul class="nav nav-tabs">
					<%= render :partial => 'lefttabs' %>
				</ul>
				<div class="tab-content">
          <%= semantic_form_for @photographer, :url => account_path, :html => {:class => 'form form-horizontal', :method => :put} do |f| %>
						<%= f.inputs :name => "Your social medias" do %>
							<%= f.input 'facebook_url', :label => "Facebook page URL", 
								:hint => "This is used for the button at the bottom of your stories", 
								:input_html => { :class => "input-xxlarge" } %>
							<%= f.input :twitter_url, :label => "Twitter URL", 
								:hint => "This is used for the button at the bottom of your stories", 
								:input_html => { :class => "input-xxlarge" } %>
							<%= f.input :blog_url, :label => "Blog URL", 
								:hint => "This is used for the blog link on the top of your website",
								:input_html => { :class => "input-xxlarge" } %>
							<% end %>

							<%= f.actions do %>
								<%= f.action :submit, :as => :button, :label => "Save", 
									:button_html => { :class => "btn btn-primary btn-large" } %>
							<% end %>
					<% end %>
				</div>
			</div>

app/views/accounts/stories.html.erb
<%= content_for :head_script do %>
<script type="text/javascript">
		$(document).ready(function() {
			// Handler for .ready() called.
				$("#sortable" ).sortable({ 
					revert: true,
					stop: function(e,ui) {
						$.ajax({
							data: $('#sortable').sortable('serialize'),
							type: 'POST',
							url: '<%= sort_photographer_path(current_user.id) %>',
							success: function () {
							// it worked!  
							},
							error: function (response) {
							// we had an error
							}
						});
						
					}
					
					});
				$("#sortable").disableSelection();

				$('body').on('hidden', '.modal', function () {
						$(this).removeData('modal');
				});
		});
</script>
<% end %>

						<div id="frontstory">
							<%= image_tag @stories.first.photos.first.image_url(:web) if @stories.any? && @stories.first.photos.any? %>
						</div>

						<div id="photos thumbnails">
							<ul id="sortable">

								<% @stories.each do |story| %>
									<li class="ui-state-default" id="sortable_<%= story.id %>">
									<a href="<%= edit_story_path(story) %>" class="thumbnail">
										<% if story.photos.any? && story.photos.first.image? %>
                    <%= image_tag story.photos.first.image_url(:thumb), width: 90, height: 90 %>
										<% else %>
											No Image
										<% end %>
									</a>
									</li>
								<% end %>

							</ul>
							<div class="clearfix"></div>
						</div>

app/views/accounts/website.html.erb
			<div class="tabbable tabs-left">
				<ul class="nav nav-tabs">
					<%= render :partial => 'lefttabs' %>
				</ul>
				<div class="tab-content">
					<%= semantic_form_for @photographer, 
          :url => account_path, 
          :html => {:class => 'form form-horizontal', :multipart => true, :method => :put} do |f| %>
						<%= f.inputs :name => "Your website" do %>

            <div class="string input optional control-group">
              <label class="control-label" for="avatar"></label>
              <div class="controls control-group">
              <% if @photographer.main_photo? %>
                <%= image_tag(@photographer.main_photo_url(:thumb),
                  :id => 'main_photo', :width => 150) %>
                </div>
                <div class="controls control-group">
                  <%= link_to 'remove the main photo?', 
                      delete_main_photo_account_path,
                      :confirm => "Are you sure?", 
                      :method => :delete %>
              <% end %>
              </div>
            </div>

              <%= f.input :main_photo, as: :file, hint: "Used for your front page" %>

							<%= f.input :specific_url, :label => "Your domain name", 
								:input_html => { :class => 'input-xlarge', :type => 'text' } %>

							<div class="controls">
									Want to use your own domain like www.<%= current_user.name ? current_user.name.downcase.gsub(' ', '') : 'domain' %>.com? 
                  <ol>
										<li>point your DNS to 91.194.60.228</li>
										<li>Fill it up here</li>
									</ol>
							</div>
						<% end %>

						<%= f.inputs :name => "Your Analytics" do %>
							<%= f.input :google_tracking_id, :label => "Google Analytics" %>
              <div class="controls">
								Example: UA-299804-4, you can get codes at <a href="https://www.google.com/analytics/">Google</a>.
							</div>
						<% end %>

							<%= f.actions do %>
								<%= f.action :submit, :as => :button, :label => "Save", 
									:button_html => { :class => "btn btn-primary btn-large" }  %>
								<% end %>
							<% end %>
				</div>
			</div>
        <script type="text/javascript">
$(function() {
  $('#user_main_photo').fileupload({
    dataType: 'json',
    url: '<%= update_main_photo_account_path %>',
    done: function(e, data) {
      $('#main_photo').attr("src", data.result.image_url);
    }
  });
});
        </script>